sudo: required

language: node_js

node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

before_script:
  - cd ./back
  - npm install    

services:
  - docker

jobs:
  include:
    - stage: test
      script:  
      - npm run test
    - stage: build BackEnd
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_URL
      - docker build --file ./back/Dockerfile --no-cache -t $REGISTRY_URL/grupoa-back .
      - docker push $REGISTRY_URL/grupoa-back
    - stage: deploy BackEnd
      script:
      - docker stack deploy -c ./back/docker-compose.yml grupo-a
    - stage: build FrontEnd
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_URL
      - docker build --file ./front/Dockerfile --no-cache -t $REGISTRY_URL/grupoa-front .
      - docker push $REGISTRY_URL/grupoa-front
    - stage: deploy FrontEnd
      script:
      - docker stack deploy -c ./front/docker-compose.yml grupo-a
