version: "3.4"

services:
  sga-api:
    image: ${PROJECT_NAME}:latest
    restart: always
    networks:
      - traefik-uneb
    deploy:
      resources:
          limits:
            memory: ${LIMIT_MEM}
      update_config:
        order: start-first
      placement:
        constraints:
          - node.labels.worker == true  
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-uneb"
        - "traefik.http.routers.${PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.rule=(Host(`${CI_ENVIRONMENT_URL}`) || Host(`www.${CI_ENVIRONMENT_URL}`)) && PathPrefix(`${BASE_PATH}`)"
        - "traefik.http.routers.${PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.entrypoints=web"
        - "traefik.http.services.${PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.loadbalancer.server.port=${PORT}"
    environment:
      ENVIRONMENT: ${CI_ENVIRONMENT_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
      DOCKER_VERSION: ${DOCKER_VERSION}
      SENTRY_KEY: ${SENTRY_KEY}
      SENTRY_PROJECT_ID: ${SENTRY_PROJECT_ID}
      SONAR_LOGIN: ${SONAR_LOGIN}
      SONAR_URL: ${SONAR_URL}
      TOKEN_GITLAB: ${TOKEN_GITLAB}
      URL_GITLAB: ${URL_GITLAB}
      BASE_PATH: ${BASE_PATH}
      TZ: ${TZ}
      SYSTEM_NAME: ${SYSTEM_NAME}
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_DATA: ${DB_DATA}
      DB_INST: ${DB_INST}      
      DISABLE_HTTP_HEALTH_CHECK: ${DISABLE_HTTP_HEALTH_CHECK}
      HTTP_HEALTH_CHECK_URL: ${CI_ENVIRONMENT_URL}${BASE_PATH}
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASS: ${LDAP_PASS}
      LDAP_DN: ${LDAP_DN}
      LDAP_URI: ${LDAP_URI}
      AD_DN: ${AD_DN}
      LIMIT_MEM: ${LIMIT_MEM}
      CERTIFICADO_KEY: ${CERTIFICADO_KEY}
      CERTIFICADO_CRT: ${CERTIFICADO_CRT}
      PORT: ${PORT}
networks:
  traefik-uneb:
    external: true    